name: Test

on: [push]

jobs:
  integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12
          cache: 'pip' # caching pip dependencies
      - uses: education/autograding-pytest-runner@main
        id: runner
      - name: Show Output
        shell: bash
        run: |
          echo "WE HERE"
          echo '${{ steps.runner.outputs.result }}'
